# Generated by Django 3.2.9 on 2021-11-29 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import graphics_base.validators.twitter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_byline', models.CharField(blank=True, max_length=250, null=True, verbose_name='Preferred byline')),
                ('google_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Gmail')),
                ('twitter_handle', models.CharField(blank=True, max_length=250, null=True, validators=[graphics_base.validators.twitter.validate_twitter_handle], verbose_name='Twitter handle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
